plan_id: pei-uccuyo-2023-2027
display_name: Plan Estratégico Institucional UCCuyo 2023-2027
years_valid: [2023, 2024, 2025, 2026, 2027]
objetivos_generales:
  1: "Desarrollar un Sistema Integral de Aseguramiento de la Calidad Institucional y Mejoramiento Continuo"
  2: "Fortalecer la integralidad de la Universidad, la vinculación con su entorno y la comunicación interna y externa"
  3: "Consolidar el Sistema Institucional de Educación a Distancia"
  4: "Desarrollar una política institucional para la jerarquización y permanencia de los recursos humanos"
  5: "Fortalecer la iniciativa y participación estudiantil y de egresados"
  6: "Consolidar la identidad cristiana, humanística y transformadora de la comunidad de la UCCuyo"
