fuente: Valores distintos del campo Unidad en export consolidado 2026
unidades_observadas:
- Coordinación General de carreras a distancia
- Coordinación General de carreras a distancia, Departamento de Educación a Distancia
- Departamento de Educación a Distancia
- Departamento de Evaluación y Acreditación
- Departamento de Graduados
- Directorio
- Escuela de Cultura Religiosa y Pastoral
- Escuela de Cultura Religiosa y Pastoral, Instituto de Formación Docentes Santa María
- Escuela de Seguridad
- Facultad Don Bosco
- Facultad de Ciencias Económicas y Empresariales San Juan
- Facultad de Ciencias Económicas y Empresariales San Luis
- Facultad de Ciencias Económicas y Empresariales San Luis, Facultad de Derecho y
  Ciencias Sociales San Juan, Facultad de Ciencias Químicas y Tecnológicas
- Facultad de Ciencias Médicas San Juan
- Facultad de Ciencias Médicas San Juan, Escuela de Cultura Religiosa y Pastoral
- Facultad de Ciencias Médicas San Luis
- Facultad de Ciencias Químicas y Tecnológicas
- Facultad de Ciencias Veterinarias
- Facultad de Ciencias Veterinarias, Facultad Don Bosco
- Facultad de Derecho y Ciencias Sociales San Juan
- Facultad de Derecho y Ciencias Sociales San Luis
- Facultad de Derecho y Ciencias Sociales San Luis, Facultad de Filosofía y Humanidades,
  Rectorado, Directorio
- Facultad de Educación
- Facultad de Educación, Departamento de Evaluación y Acreditación
- Facultad de Filosofía y Humanidades
- Facultad de Filosofía y Humanidades, Escuela de Cultura Religiosa y Pastoral
- Jefatura de Sistemas
- Observatorio de Inteligencia Artificial
- Orientación Universitaria
- Rectorado
- Rectorado, Consejo Superior
- Rectorado, Consejo Superior, Directorio
- Rectorado, Departamento de Educación a Distancia
- Rectorado, Departamento de Educación a Distancia, Coordinación General de carreras
  a distancia
- Rectorado, Directorio
- Rectorado, Secretaría Académica
- Rectorado, Secretaría de Extensión
- Secretaría Académica, Coordinación General de carreras a distancia
- Secretaría Académica, Coordinación General de carreras a distancia, Jefatura de
  Sistemas
- Secretaría Investigación
- Secretaría de Extensión
- Área de Orientación Universitaria
alias:
  Secretaría Investigación: Secretaría de Investigación
